# Alembic configuration file

[alembic]
script_location = %(here)s/migrations
prepend_sys_path = .
path_separator = os

# We DO NOT use sqlalchemy.url here.
# Flask's create_app() provides the correct DB URL for both
# local (SQLite) and production (PostgreSQL).
sqlalchemy.url = sqlite:///placeholder.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
