services:
  - type: web
    name: nofooltools
    env: python
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        value: ${nofooltools-db.DATABASE_URL}
      - key: PYTHON_VERSION
        value: 3.10
      - key: WEB_CONCURRENCY
        value: 2
      - key: GUNICORN_CMD_ARGS
        value: --timeout 120 --log-level info

databases:
  - name: nofooltools-db
    plan: free
    region: frankfurt
